### ISSUE TITLE
Apache server failed to load passenger module on openSUSE Leap 15.4

### ISSUE THREAD

**Issue by pbartfai** [openSUSE/open-build-service#14350]
# Issue Description
Apache server failed to start with error message:
```
Invalid command 'PassengerSpawnMethod', perhaps misspelled or defined by a module not included in the server configuration
```

Expected Result
============
Apache server should run

How to Reproduce
===============
Install OBS on openSUSE Leap 15.4 as recommended:
```
# zypper ar -f https://download.opensuse.org/repositories/OBS:/Server:/2.10/15.4/OBS:Server:2.10.repo
# zypper in -t pattern OBS_Server
# /usr/lib/obs/server/setup-appliance.sh --force --non-interactive
# httpd -X
AH00526: Syntax error on line 7 of /etc/apache2/vhosts.d/obs.conf:
Invalid command 'PassengerSpawnMethod', perhaps misspelled or defined by a module not included in the server configuration
```

Further Information
===============
version 2.10.20

following lines are missing from /etc/apache2/loadmodule.conf:
```
LoadModule passenger_module               /usr/lib64/apache2/mod_passenger.so
LoadModule xforward_module                /usr/lib64/apache2/mod_xforward.so
LoadModule headers_module                 /usr/lib64/apache2-prefork/mod_headers.so
LoadModule proxy_module                   /usr/lib64/apache2-prefork/mod_proxy.so
```

**Comment by pallaswept** [comment]
Same issue here. Adding the missing lines still leaves us with another error, PassengerPreStart cannot occur within <VirtualHost> section, and apache won't start.

The pre-packaged appliances are running out-of-date packages and even if the system is upgraded to 15.4, still generates errors which builds.opensuse.org does not. 

Is there any way to get a working local OBS appliance at the moment?

**Comment by hennevogel** [comment]
@pallaswept OBS:Server:Unstable is that, *very* unstable. It is the latest code updated dozens of times per day. You will run frequently into problems that you will only be able to solve with intricate knowledge of the inner workings of OBS and the frameworks, tools etc that is makes use of. You will also be alone as we *will not* support you with this. You have been warned :)

**Comment by pallaswept** [comment]
> @pallaswept OBS:Server:Unstable is that, _very_ unstable. It is the latest code updated dozens of times per day. You will run frequently into problems that you will only be able to solve with intricate knowledge of the inner workings of OBS and the frameworks, tools etc that is makes use of. You will also be alone as we _will not_ support you with this. You have been warned :)

Thanks, I took the name as such a warning. If there's a repo that has the above issues fixed and also isn't 'unstable' and unsupported, I'd love to know of it!

**Comment by hennevogel** [comment]
> If there's a repo that has the above issues fixed and also isn't 'unstable' and unsupported, I'd love to know of it!

If by above issues you mean the passenger problems on 15.4: there isn't yet. But its on the TODO to move 2.10 to a new base distro, so far we are still on 15.3.

**Comment by pallaswept** [comment]
> > If there's a repo that has the above issues fixed and also isn't 'unstable' and unsupported, I'd love to know of it!
> 
> If by above issues you mean the passenger problems on 15.4: there isn't yet. But its on the TODO to move 2.10 to a new base distro, so far we are still on 15.3.

By above issues I meant all of those mentioned so far; the passenger problems, the certs, the firewall config, worker config, etc.

So there's nothing available to us that works then, that's nice to know because at least I can stop trying to do the impossible :) It is a shame though, because it makes it impossible to develop apps for opensuse in private.

I did try to upgrade (as per the supported instructions) the 15.3 appliance to 15.4, but it didn't solve the issues. Of course, that's because the server config files have to change to match, and those updated server configs do exist, but only in unstable.

**Comment by hennevogel** [comment]
@pallaswept let me unpack. You have several issues with 2.10 running on 15.4. You also seem to have a general problem with certificates on 2.10. You should file those individual issues if you want to make sure they are not getting overlooked if we move for instance move to 15.4 (or any other later version) as base OS. It will also give OBS contributors a chance to work on them individually. Please don't expect us to know everything you know and have all the experience with this you have. We are a bunch of open source developers trying to do the best job we can, given what we know, our skills and abilities, the resources available to us, and the situation at hand...

**Comment by pallaswept** [comment]
> @pallaswept let me unpack. You have several issues with 2.10 running on 15.4.

That's correct, although not just with 15.4, I've tried 15.3, 15.4, 15.5, and even tumbleweed. I've been unable to find any way to run an instance of OBS which works as build.opensuse.org does, in a private server. I followed all of the official documentation, starting with running the appliance installation ISO, then the appliance disk images (qcow images, specifically, as I'm using opensuse as a host and virt-manager with qemu+kvm is the native way to run VMs), then fresh installations of opensuse leap (and even tw that one time) and adding the repo and packages and running the script as per the readme. None resulted in a working instance.

> You also seem to have a general problem with certificates on 2.10. 

Yes, the script that ships with the images and which is on the 2.10 repos automatically generates 1024 bit SSL certs, which generate errors in both osc and zypper. This is because the more recent versions of the applications on the clients (15.3 being quite old to the point of warning you on the server when you run zypper that the packages are out of date) expect more secure certs, and will not function without them. I figured out (I do try to solve my problems alone so as to avoid troubling you) that removing the certs would cause them to be automatically regenerated, and that I could change that one line in the script to have it generate a stronger cert; to quote my notes on this:
```
sudo sed -i 's/1024/2048/' /usr/lib/obs/server/setup-appliance.sh 
mkdir /srv/obs/certs/old
mv /srv/obs/certs/* /srv/obs/certs/old/
reboot now
```
but I did not report the issue as the new versions of the build script already generate 4096b certs so it is clear that your team is already aware of the problem and solution and a fix is in place. It's just that that fix isn't in any of the released versions of the script. It's in the source, no longer directly in the file I patch above, but that script now sources functions (looks much cleaner now!) and [one of them has the specification for 4096b certs](https://github.com/openSUSE/open-build-service/blob/master/dist/functions.setup-appliance.sh#L359) (BTW, github's search function is broken, so don't bother searching for the "check_server_cert" function because according to the results it doesn't exist in your source code....even though I just linked it twice :D The trouble is, it is in the source, but it isn't released anywhere - except that unstable repo, which uses the fancy new script and works like a charm.

> You should file those individual issues ... Please don't expect us to know everything you know and have all the experience with this thatr you have.

I'm sorry if it came across that way. I didn't report them just because I know you're already on top of it and I didn't want to add known, fixed issues to your list and be an annoyance. I just briefly mentioned them above kinda thinking you'd know what I was referring to since you'd already fixed it.

> We are a bunch of open source developers trying to do the best job we can, given what we know, our skills and abilities, the resources available to us, and the situation at hand...

It's a tough job and can be thankless at times, so I'm very sorry if I came across that way. I'm just trying to keep it brief and not get under your feet, but obviously it came across all wrong. My bad!

So, I'm not sure if I should be filing issues for everything I've come across which is fixed in the source but not released in the repos/images/installers. I think  it sounds like what I'm really waiting on here is for 2.11 but I was operating under the misgiving that what I was waiting for was for 2.10 to be updated. Please forgive my ignorance, I'm not sure how it's meant to work so I'm not sure what I should do. I'm trying to do something about that ignorance by building an OBS instance but you can see how I'm going with that :D

**Comment by pallaswept** [comment]
> Same issue here. Adding the missing lines still leaves us with another error, PassengerPreStart cannot occur within section, and apache won't start.

Looking into this, I came across other projects where the same issue had been brought up, and the suggestion from the passenger devs was to simply move the line outside of the <VirtualHost> directive, so I did. Before:

```

<VirtualHost *:443>
        ServerName api

	#  General setup for the virtual host
        DocumentRoot  "/srv/www/obs/api/public"
	ErrorLog /srv/www/obs/api/log/apache_error.log
	TransferLog /srv/www/obs/api/log/apache_access.log

        # Enable maintenance mode. All requests will be redirected
        # to the maintenance page and return 503 as http status.
        # Start your apache with -D MAINTENANCE to enable this.
        # On (open)SUSE you can do this by setting
        # APACHE_SERVER_FLAGS="MAINTENANCE" in /etc/sysconfig/apache
        <IfDefine MAINTENANCE>
          ErrorDocument 503 /503.html
          RewriteEngine on
          RewriteCond %{REQUEST_URI} !=/503.html
          RewriteRule ^ - [R=503,L]
        </IfDefine>

        PassengerPreStart https://api
        PassengerMinInstances 2
.....

The warning message is gone, apache starts fine, and the API works fine. Another easy fix for you this morning let's make that 992 issues 990 real quick shall we? :)
```

After:

```
....
PassengerPreStart https://api

<VirtualHost *:443>
        ServerName api

	#  General setup for the virtual host
        DocumentRoot  "/srv/www/obs/api/public"
	ErrorLog /srv/www/obs/api/log/apache_error.log
	TransferLog /srv/www/obs/api/log/apache_access.log

        # Enable maintenance mode. All requests will be redirected
        # to the maintenance page and return 503 as http status.
        # Start your apache with -D MAINTENANCE to enable this.
        # On (open)SUSE you can do this by setting
        # APACHE_SERVER_FLAGS="MAINTENANCE" in /etc/sysconfig/apache
        <IfDefine MAINTENANCE>
          ErrorDocument 503 /503.html
          RewriteEngine on
          RewriteCond %{REQUEST_URI} !=/503.html
          RewriteRule ^ - [R=503,L]
        </IfDefine>

        PassengerMinInstances 2
.....

```

**Comment by johanneskastl** [comment]
For the record, I wrote a Ansible role that allows to me setup a OBS Server. I created a working OBS server on 15.3, and just tested, the role also deploys successfully on 15.4.
(Working => the UI starts. I can successfully connect on ports 80, 82 and 443 (HTTPS). I have not yet tested workers or anything like that, I was glad that WebUI is reachable...)

These are the apache related steps that solve the apache/passenger/... errors:
https://github.com/johanneskastl/ansible-role-obs_server/blob/main/tasks/apache2.yml#L48

**Comment by pallaswept** [comment]
> (Working => the UI starts. I can successfully connect on ports 80, 82 and 443 (HTTPS). I have not yet tested workers or anything like that, I was glad that WebUI is reachable...)

You're going to need to configure the workers manually and also update the SSL certs and the script that creates them (I mentioned this issue and[ its workaround in the thread above](https://github.com/openSUSE/open-build-service/issues/14350#issuecomment-1610367738)) as well as fixing systemd unit files as per https://github.com/openSUSE/open-build-service/issues/14588 if you're separating your data from the appliance (which I definitely would if I were you, since the current appliance is clearly broken in several ways and you're not going to want to lose all your data when a new, working one is released)

**Comment by pbartfai** [comment]
Fixed in last package.

**Comment by pallaswept** [comment]
> Fixed in last package.

Awesome, thanks so much and it's great news to know there's a new package out. Has that been rolled into the appliance images (ie https://openbuildservice.org/download/other/) or does this fix only apply to upgrades and manual installs on existing 15.3 systems?

**Comment by pallaswept** [comment]
@pbartfai Thought I should @ you in case you've unsubscribed when closing this and missed the above message :)

**Comment by pallaswept** [comment]
> > Awesome, thanks so much and it's great news to know there's a new package out. Has that been rolled into the appliance images (ie https://openbuildservice.org/download/other/) or does this fix only apply to upgrades and manual installs on existing 15.3 systems?
> 
> I installed a brand new openSUSE Leap 15.5 and installed OBS on top of it.

I notice that since my original post above, the https://openbuildservice.org/ pages have all changed to read 15.5 where they used to use 15.3, so it looks like you've created the new standard. This is fantastic news. Thank you very much, I've been waiting for months to be able to get OBS working locally without a lot of awkward manual intervention to apply fixes, it's a real relief (and will significantly shorten my process documentation!) that the new package versions are rolling out. Thanks, and thanks again!

**Comment by rhabacker** [comment]
This is still an issue in the apache configuration file for apache 2.4, see https://github.com/openSUSE/open-build-service/blob/17f586d289a661c05dfcf269bdfc5fd89dd5ecf8/dist/obs-apache24.conf#L62
