### ISSUE TITLE
Please upload zsync files for KIWI images

### ISSUE THREAD

**Issue by probonopd** [openSUSE/open-build-service#3193]
Issue/Feature description
====================

Please upload zsync files for KIWI Images (such as Live ISOs), this way one could easily update e.g., from the previous to the current Tumbleweed ISO without having to re-download the entire image, but only the blocks that have actually changed. Ubuntu has been using zsync for this purpose since many years.

The `.zsync` file should (also) be available under a fixed URL, e.g., `*-latest-*`, similar to how OBS does it for AppImages.

Expected result
============

Instead of having to download the entire image when it is updated, I can use zsync to only download the blocks that have changed.

Further information
===============
* zsync is already installed for livebuild: https://github.com/openSUSE/obs-build/blob/0a5092d74c2b85e71b1f6233746bf1db56a66e04/Build.pm#L473
* zsync handling for AppImage is already implemented: https://github.com/openSUSE/open-build-service/blob/84bf4c1bf50c8c07d0c034343c5d87d944330eac/src/backend/bs_publish#L873

**Comment by adrianschroeter** [comment]
this would be something for kiwi bundler @schaefi , what do you think  about this?

**Comment by schaefi** [comment]
Sounds like a very good idea. I have opened an issue for KIWI here:

* https://github.com/SUSE/kiwi/issues/364

Please comment on the issue in kiwi if implementation details from the obs side are needed.
iirc the zsyncmake call needs a url suitable for obs, where could kiwi get this information from ?

**Comment by adrianschroeter** [comment]
done, let's close this one here then.

**Comment by schaefi** [comment]
@adrianschroeter could you please review: https://github.com/SUSE/kiwi/issues/390

If this one makes it into kiwi the buildservice needs to be adapted too, in order to provide the zsync source information to the bundler call

**Comment by probonopd** [comment]
What is the progress here, who would need to do what so that a zsync file would start showing up in http://download.opensuse.org/repositories/home:/probono:/branches:/KDE:/Medias/images/iso/?

**Comment by probonopd** [comment]
Ping

**Comment by probonopd** [comment]
@adrianschroeter 

> done, let's close this one here then.

Please revisit this. `zsync` files are still missing from download directories like https://download.opensuse.org/distribution/leap/15.0/live/ and it would really be cool to have them, especially for the Tumbleweed Live ISOs.

**Comment by probonopd** [comment]
Please reopen this.

I am running `openSUSE-Tumbleweed-KDE-Live-x86_64-Snapshot20180530-Media.iso` and I would like to "upgrade" to the latest one, `openSUSE-Tumbleweed-KDE-Live-x86_64-Snapshot20180606-Media.iso`. If there was a `.zsync` file, I would have to download only a few MB. Since there is none, I need to re-download the full ISO image.
