### ISSUE TITLE
[backend] DoD package resolution failure

### ISSUE THREAD

**Issue by mmohring** [openSUSE/open-build-service#4121]
Issue/Feature description
====================
Name resolution fails for a recently updated package in openSUSE Leap 42.2 and 42.3.

Expected result
============
Should behave as if the packages were not loaded by DoD but when present in :full directory.

How to Reproduce
===============
1. recently, mysql-community-server was patched in openSUSE:Leap:42.{2,3}:Update
2. obs-server has a build requirment to mysql-community-server
3. If you build obs-server against openSUSE:Leap:42.{2,3}:Update, it results in a expansion error

Further information
===============
* Error message: mysql-community-server-errormessages = 5.6.38 needed by mysql-community-server
* I use a private instance of git master as new as b.o.o

If I download the mysql-community-server-errormessages.rpm into :full and remove the DoD from our local openSUSE:Leap:42.{2,3}:Update.xml and run a rescan repository, the expansion error goes away.

**Comment by mmohring** [comment]
I am using:

`
    <download arch="x86_64" url="http://download.opensuse.org/update/leap/42.2/oss" repotype="rpmmd">
      <archfilter>x86_64,noarch</archfilter>
    </download>
`

and

`
    <download arch="x86_64" url="http://download.opensuse.org/update/leap/42.3/oss" repotype="rpmmd">
      <archfilter>x86_64,noarch</archfilter>
    </download>
`

as download repositories.

**Comment by mmohring** [comment]
I have noticed this with other updates, dito. E.g. java-1.8 security update vs. mozilla-nss.

**Comment by mmohring** [comment]
@mls this is an issue for you i guess. Do you need more info ? Can you provide some info how DoD generates different package dependencies as the normal binary package parser does ? Does it use the repo info to generate the :full.solv database ?

**Comment by seife** [comment]
Hi Martin,
in order to have @mlschroe be able to reproduce and fix the issue, you probably need to provide exact instructions on how to reproduce the issue on a plain, clean obs install.

See https://lists.opensuse.org/opensuse-buildservice/2016-11/msg00020.html and https://lists.opensuse.org/opensuse-buildservice/2016-11/msg00024.html to see how the similar issue #2296 was solved :-)

**Comment by seife** [comment]
This is probably the same issue as #8012: 42.3 GA had `mysql-community-server-5.6.36-25.1.x86_64.rpm`, while the update repo has first `mysql-community-server-errormessages-5.6.37-27.1.x86_64.rpm`, but then switches to `mysql-community-server-errormessages-5.6.38-30.1.noarch.rpm`

So it is again a x86_64 -> noarch switch, that perl-BSSolv cannot handle properly.

**Comment by mmohring** [comment]
> Hi Martin,
> in order to have @mlschroe be able to reproduce and fix the issue, you probably need to provide exact instructions on how to reproduce the issue on a plain, clean obs install.
> 
> See https://lists.opensuse.org/opensuse-buildservice/2016-11/msg00020.html and https://lists.opensuse.org/opensuse-buildservice/2016-11/msg00024.html to see how the similar issue #2296 was solved :-)

What do you mean with "you probably need to provide exact instructions" ? I described the issue in my initial report and how I worked around. This issue is still there, with the Leap 42.3 Updates. Since now this distro is EOL, you can reproduce it as long as 42.3 remains downloadable. I think the bug is a dublicate of yours. You have it now reproducable in b.o.o. I guess the fix is the same. The bug still happens with the latest OBS git commit, which is commit e4d3163210f30573cc48eeb5956289696d5ed2be . So if your bug gets fixed, I am sure this one is fixed too.

**Comment by mmohring** [comment]
> This is probably the same issue as #8012: 42.3 GA had `mysql-community-server-5.6.36-25.1.x86_64.rpm`, while the update repo has first `mysql-community-server-errormessages-5.6.37-27.1.x86_64.rpm`, but then switches to `mysql-community-server-errormessages-5.6.38-30.1.noarch.rpm`
> 
> So it is again a x86_64 -> noarch switch, that perl-BSSolv cannot handle properly.

That is exactly what I want to say :+1:

**Comment by seife** [comment]
You neet to tell mls exactly what steps he needs to follow to reproduce it on a clean install. Your description is waaaaaay toooo generic ;-)

See my first mentioned email where I described it totally foolproof ;-)

**Comment by mmohring** [comment]
You did now provided the reproducable example on b.o.o. So I don't have to do it anymore :+1:

**Comment by mmohring** [comment]
I think I found the place in the code responsible. One of the pkg management functions in src/backend/bs_dodup do not handle the case with <archfilter>list of archs</archfilter> to take into consideration when computing the highest version.

**Comment by seife** [comment]
I do not have any archfilter set in my dod repos, yet still hit the issue, so I'm not sure you are on the right track.

I think the issue is with BSSolv not getting the correct highest version when multiple archs are available for a package, but then I do not understand the resolver code at all ;-)

**Comment by mmohring** [comment]
I am currently testing my fix. I will post it The b.o.o repo for SLE uises arch filters. Also all other distros like Leap 42.3, 15.x etc. are using those filters for DoD repos. All rpm repos are affected. Causes a lot of rebuilds. But they work now-. I will report tomorrow.

**Comment by mmohring** [comment]
> I am currently testing my fix. I will post it The b.o.o repo for SLE uses arch filters (take a look with meta prj on the distro). Also all other distros like Leap 42.3, 15.x etc. are using those filters for DoD repos. All rpm repos are affected. Causes a lot of rebuilds. But they work now-. I will report tomorrow.

**Comment by mmohring** [comment]
Since @mlschroe will review my patch anyway, all is fine :-)

**Comment by marcus-h** [comment]
On 2019-08-08 11:42:42 -0700, Stefan Seyfried wrote:
> I think the issue is with BSSolv not getting the correct highest version when multiple archs are available for a package, but then I do not understand the resolver code at all ;-)
>
Note: I have not really investigated this issue at all but if your
claim is right, then have a look at create_considered in BSSolv.xs: if
the arch-specific solvable is "considered" before the noarch one,
the noarch one will be discarded (regardless of the version) (grep
for ARCH_NOARCH).

**Comment by mmohring** [comment]
Hi Marcus, the bug *is not* in BSSolv but simply in src/backend/bs_dodup. I have a patch I am currently testing. I will post it tomorrow when all the rebuilds in my system are passed through. The repo parser in src/backend/bs_dodup for rpm repos does simply not compute the highest version of a packages in *all archfilter* archs. @marcus-h, do you remember, we wrote the initial DoDo ? Long time ago....

**Comment by mmohring** [comment]
I have now created a patch in #8064. Please review it.

**Comment by seife** [comment]
> Note: I have not really investigated this issue at all but if your claim is right, then have a look at create_considered in BSSolv.xs: if the arch-specific solvable is "considered" before the noarch one, the noarch one will be discarded (regardless of the version) (grep for ARCH_NOARCH).

You are right.
Original bs_dodup, but BSSolv.xs changed like this:

```
old: openSUSE.org:OBS:Server:2.10/perl-BSSolv
new: Infrastructure:OBS:2.10/perl-BSSolv rev None
Index: BSSolv.xs
===================================================================
--- BSSolv.xs (revision 20)
+++ BSSolv.xs (revision 2)
@@ -2676,6 +2676,7 @@
              sb = pool->solvables + pb;
              if (!unorderedrepos && s->repo != sb->repo)
                continue;       /* first repo wins */
+#if 0
              /* take package if it has a higher arch/version */
              if (s->arch != sb->arch)
                {
@@ -2691,6 +2692,8 @@
                    }
                }
              else if (s->evr != sb->evr)
+#endif
+             if (s->evr != sb->evr)
                {
                  /* same repo, check versions */
                  int r;
```
Basically disable the "priority by arch" stuff and let it just sort out versions.
Seems to work well.

**Comment by mlschroe** [comment]
Yes, the noarch handling is broken if we compare the arch first. I now moved the arch handling after the version comparison, see: https://github.com/openSUSE/perl-BSSolv/commit/0416944cf8dcd8b98d8ed321fe8fb7c600ce4372

**Comment by seife** [comment]
https://github.com/openSUSE/perl-BSSolv/commit/0416944cf8dcd8b98d8ed321fe8fb7c600ce4372 works well at my installation.

**Comment by mmohring** [comment]
OK. So let me try it also.

**Comment by mmohring** [comment]
Hi, I packaged openSUSE/perl-BSSolv@0416944 and deployed it on all our systems for testing, without my proposed DoD patch. Seems to work. I keep an eye on it the next days.
